### ISSUE TITLE
elfutils unwinding may be busted on Linux aarch64 when unwinding muslc

### ISSUE THREAD

**Issue by pablogsal** [bloomberg/pystack#3]
When I try to unwind in an `Alpine Linux` docker container in a `aarch64` host seems that `elfutils` goes brrrrrrrrrrrrrrrrrrrrrrrrrrrr and chokes with an instruction pointer and keeps looping on it, so unwinding takes as much as the heat death of the universe.

We should try to add some magic sparkles so that unwinding doesn't take forever.

**Comment by godlygeek** [comment]
I've also sent a bug report to the musl developers for this. https://www.openwall.com/lists/musl/2023/03/31/2
