### ISSUE TITLE
Segments can be missing read permissions

### ISSUE THREAD

**Issue by pablogsal** [bloomberg/pystack#4]
For some reasons (probably some security shenanigans) some segments lack all permissions and in particular the read permission. This can cause `process_vm_readv` to fail as if the memory address that we requested is invalid and does not exist.

We should filter these segments when we do our analysis to locate the relevant segments for the heap, bss....etc

**Comment by godlygeek** [comment]
#19 and #21 fixed the issue where multiple heap mappings are reported.
#25 fixes the 3 smoke tests that are failing on 3.11
