### ISSUE TITLE
Utilize `pkgconfig` to find elfutils

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/pystack#54]
The https://pypi.org/project/pkgconfig/ library provides a way to determine the right compiler and linker flags to use for building against a particular C library. We're not currently leveraging this, and are instead assuming that the elfutils headers and libraries are in the system's default search paths. We should update our `setup.py` to try to use `pkgconfig` to locate the right flags for building and linking against `libelf` and `libdw`, but fall back to our current behavior if the `pkgconfig` query fails.

**Comment by jay-z007** [comment]
I'll take this

**Comment by apurvakhatri** [comment]
pkgconfig raises EnvironmentError, If pkg-config is not on the path. (_As per pkgconfig Documentation_). How to include system package (pkg-config) in python project? If yes, what is the best practice? If no, should we update the docs for the user to add pkg-config to path before building? 
Also, I tested building editable by adding flags to PYSTACK_EXTENSION.extra_link_args & PYSTACK_EXTENSION.extra_compile_args. However, I am unable to understand the fallback behavior. How to go around implementing the fallback? Any help would be greatly appreciated. Thank you!

**Comment by godlygeek** [comment]
> pkgconfig raises EnvironmentError, If pkg-config is not on the path. (_As per pkgconfig Documentation_). How to include system package (pkg-config) in python project? If yes, what is the best practice? If no, should we update the docs for the user to add pkg-config to path before building?

There's no way for a Python package to declare a dependency on a system package. We can mention that users should install `pkg-config` in the [Building from Source](https://github.com/bloomberg/pystack/blob/main/README.md#building-from-source) section of the README, though, like we do for `libdw` and `libelf` themselves.

> I am unable to understand the fallback behavior. How to go around implementing the fallback?

Just like you're doing - catching and ignoring the two possible exceptions that the `pkgconfig` module can raise (an `EnvironmentError` for `pkg-config` itself not being installed, and `pkgconfig.PackageNotFoundError` for it being installed but not being able to find or parse the `.pc` files). If either of those conditions happens, we just fall back to our current hardcoded `libraries=`.

> If you feel the linked PR is correct then please let me know. Any help would be greatly appreciated.

It looks like pretty much what I was picturing, but you're making it a little tougher than necessary! I'd do one thing a little bit differently: instead of calling `pkgconfig.cflags` and `pkgconfig.libs` directy, we can call `pkgconfig.parse`. It returns a dictionary containing arguments that are appropriate for passing to the `Extension` constructor, so we should be able to just do something like:

```py
library_flags = {libraries=["elf", "dw"]}
try:
    library_flags = pkgconfig.parse("libelf libdw")
except EnvironmentError:
    print("pkg-config not installed, falling back to static flags")
    print("Falling back to static flags")
except pkgconfig.PackageNotFoundError:
    print("pkg-config configuration for libelf and libdw not found.")
    print("Falling back to static flags")
```
And then we can just remove the `libraries=["elf", "dw"]` from the `Extension()` call and pass `**library_flags` instead.
