### ISSUE TITLE
Require news entries for new PRs

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/pystack#55]
Leverage the https://github.com/brettcannon/check-for-changed-files GitHub Action to require that every PR either has a news entry in `news/*.rst` or a `skip news` label applied to the PR.

**Comment by austinlg96** [comment]
I can take a look into this one.

**Comment by gusmonod** [comment]
The PR above fixes this issue.

**Comment by gusmonod** [comment]
Thank you @austinlg96 !
