### ISSUE TITLE
`make clean` breaks virtualenvs stored inside the repo clone

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/pystack#56]
If you create a virtualenv inside a clone of the repo, running `make clean` will break it by removing all of the `*.so` files inside of it. We should improve our `make clean` to only remove files that we know we've created.

**Comment by godlygeek** [comment]
It's a bit trickier than that, since you might have _multiple_ virtualenvs all in the same repo root. What you're proposing would stop it from breaking the active virtualenv, but wouldn't stop it from breaking deactivated ones.

The safer option is enumerating the files that we expect to be created by commands in the makefile, and only removing those, rather than using a recursive wildcard.

**Comment by jay-z007** [comment]
I'll take this
