### ISSUE TITLE
Additonal Documentation and make Targets for Docker

### ISSUE THREAD

**Issue by Helithumper** [bloomberg/pystack#83]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

When working on this project from a MacOS device, I had issues with a few different files, in particular, errors related to `elf.h`. To solve this, I used the included Dockerfile to work on the code (with https://github.com/bloomberg/pystack/issues/69 to fix an issue there). There is a lack of documentation in the README.md about using Docker with this project, however there is a Dockerfile provided.

### Describe the solution you'd like

I think adding additional info to `README.md` around using Docker with this project would be useful. In particular,
- Adding a copy-paste-able command `docker run -it -v $(pwd):/src $IMAGENAME` and `docker build . -t $IMAGENAME`
- Possibly adding a target to the `Makefile` to build the image and run bash in a container based on that image.

### Alternatives you considered

Alternatively, a `Vagrantfile` could also be created to spin up a Linux VM for working on development in for users not in a Linux system.

Documentation on how to run this program natively on MacOS would also be another good idea.

**Comment by Helithumper** [comment]
I can work on this as well, I have the commands in a version I have locally when I was getting this setup and would just need to modify the `README.md` to complete this out I think

**Comment by godlygeek** [comment]
This sounds reasonable to me, but I don't use Docker as part of my daily workflow, so I'm going to defer to @pablogsal about whether this makes sense, and how exactly it should work.

**Comment by Helithumper** [comment]
Have this working on my machine aside from unit tests, it appears that they're having issues due to how the files are processed:
```
_____________________________________________ test_extract_executable[python3.8] _____________________________________________
python = ((3, 8), PosixPath('/usr/bin/python3.8'))
tmpdir = local('/tmp/pytest-of-root/pytest-2/test_extract_executable_python3')

    @ALL_PYTHONS
    def test_extract_executable(python: PythonVersion, tmpdir: Path) -> None:
        """Generate a core file for a process with a single thread and check
        that we can extract the executable that was used to create the core file"""
    
        # GIVEN
        _, python_executable = python
    
        # WHEN
>       with generate_core_file(
            python_executable, TEST_SINGLE_THREAD_FILE, tmpdir
        ) as core_file:

tests/integration/test_core_analyzer.py:465: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.10/contextlib.py:135: in __enter__
    return next(self.gen)
tests/utils.py:112: in generate_core_file
    with subprocess.Popen(
tests/utils.py:112: in generate_core_file
    with subprocess.Popen(
/usr/lib/python3.10/bdb.py:90: in trace_dispatch
    return self.dispatch_line(frame)
/usr/lib/python3.10/bdb.py:114: in dispatch_line
    self.user_line(frame)
/usr/lib/python3.10/pdb.py:253: in user_line
    self.interaction(frame, None)
/usr/lib/python3.10/pdb.py:348: in interaction
    self._cmdloop()
/usr/lib/python3.10/pdb.py:313: in _cmdloop
    self.cmdloop()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <_pytest.debugging.pytestPDB._get_pdb_wrapper_class.<locals>.PytestPdbWrapper object at 0xffff8af1dea0>, intro = None

    def cmdloop(self, intro=None):
        """Repeatedly issue a prompt, accept input, parse an initial prefix
        off the received input, and dispatch to action methods, passing them
        the remainder of the line as argument.
    
        """
    
        self.preloop()
        if self.use_rawinput and self.completekey:
            try:
                import readline
                self.old_completer = readline.get_completer()
                readline.set_completer(self.complete)
                readline.parse_and_bind(self.completekey+": complete")
            except ImportError:
                pass
        try:
            if intro is not None:
                self.intro = intro
            if self.intro:
                self.stdout.write(str(self.intro)+"\n")
            stop = None
            while not stop:
                if self.cmdqueue:
                    line = self.cmdqueue.pop(0)
                else:
                    if self.use_rawinput:
                        try:
>                           line = input(self.prompt)
E                           OSError: [Errno 9] Bad file descriptor

/usr/lib/python3.10/cmd.py:126: OSError
```

Seeing if I can figure out what's going on here

**Comment by pablogsal** [comment]
Let me see if I can reproduce this error in my mac laptop

**Comment by pablogsal** [comment]
Ah, @godlygeek isn't this the error you found with the elfutils version that was closing file descriptors?

**Comment by pablogsal** [comment]
@Helithumper can you try to install `pytest-forked` and run pytest with `--forked`?

**Comment by pablogsal** [comment]
@Helithumper We can export a PYTEST_OPTIONS env var for the container that uses `--forked` for the time being.

**Comment by godlygeek** [comment]
> Ah, @godlygeek isn't this the error you found with the elfutils version that was closing file descriptors?

The "bad file descriptor" is definitely that, yeah. I thought Ubuntu 22.04 picked up a new enough version of elfutils to not have that bug, but I guess not... ☹️

**Comment by godlygeek** [comment]
I wonder if we ought to just compile elfutils in the docker image? If we do it in a layer of its own, it can be cached, and would definitely guarantee people wouldn't hit this error. The `pytest-forked` option is a hack that mostly works, but it does break some things - I think someone at the sprints said that reporting test coverage doesn't play nicely with running each test in a subprocess. It also seems that `--pdb` doesn't play nicely with `pytest-forked`.

**Comment by gusmonod** [comment]
> I wonder if we ought to just compile elfutils in the docker image? If we do it in a layer of its own, it can be cached, and would definitely guarantee people wouldn't hit this error. The `pytest-forked` option is a hack that mostly works, but it does break some things - I think someone at the sprints said that reporting test coverage doesn't play nicely with running each test in a subprocess. It also seems that `--pdb` doesn't play nicely with `pytest-forked`.

I can confirm that at least the way it is configured now, coverage is not reported properly when using `pytest-forked`.

**Comment by pablogsal** [comment]
Closing this as #87 has been landed
