### ISSUE TITLE
Reach 100% coverage of Cython code

### ISSUE THREAD

**Issue by gusmonod** [bloomberg/pystack#88]
Our Python + Cython coverage currently is close to (but not quite at) 100%. #79 has made the Python code 100% covered, but there are a few things in `src/pystack/_pystack.pyx` that still aren't covered, and #86 will force the `--cov-fail-under=100` to be bumped back to a lower minimum coverage. Let's get that up to 100% again, including Cython this time!

**Comment by pablogsal** [comment]
Closing this as #51 has been landed
